id: PC591CF1F
initial_creation_type: input
source_metadata:
  title: Trisaṃvara
  parent: 1. Commentaries on the Eighteen Great Treatises
  source: https://sakyalibrary.com
  bases:
    a0a8:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ས་སྐྱ་པཎྜི་ཏ།
      base_file: a0a8.txt
      order: 1
    9afd:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་བཤད་རྒྱལ་བའི་གསུང་རབ་ཀྱི་དགོངས་པ་གསལ་བ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 9afd.txt
      order: 2
    817f:
      title: སྡོམ་གསུམ་རབ་དབྱེའི་སྤྱི་དོན་ཡིད་བཞིན་ནོར་བུ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 817f.txt
      order: 3
    8ea1:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་གཞུང་ལུགས་ལེགས་པར་བཤད་པ་བཞུགས་སོ།།་་་་རྩ་བའི་པོད་གཅིག་ཡིན་ཀྱང་མ་དཔེར་པོད་གསུམ།
      author: སྤོས་ཁང་པ་རིན་ཆེན་རྒྱལ་མཚན།
      base_file: 8ea1.txt
      order: 4
    5fe1:
      title: སྡོམ་གསུམ་རབ་དབྱེའི་དཀའ་འགྲེལ་སྦས་དོན་གནད་ཀྱི་སྙིང་པོ་གསལ་བྱེད་ལས། ཕྱག་ཆེན་རྩོད་སྤོང་སྐབས་ཀྱི་ལེགས་བཤད་ཉི་མའི་འོད་ཟེར་བྱ་བ་བཞུགས་སོ།།
      author: མང་ཐོས་ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
      base_file: 5fe1.txt
      order: 5
    f3ff:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་དཀའ་བའི་གནད་རྣམ་པར་འབྱེད་པ་ཞིབ་མོ་རྣམ་འཐག
      author: གློ་བོ་མཁན་ཆེན་བསོད་ནམས་ལྷུན་གྲུབ།
      base_file: f3ff.txt
      order: 6
    9e9a:
      title: ཆོས་དང་ཆོས་མིན་པ་རྣམ་པར་འབྱེད་པའི་བསྟན་བཅོས་སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་པར་བཤད་པ་ཐུབ་བསྟན་གསལ་བའི་སྒྲོན་མེ།
      author: དགེ་སློང་ཀུན་དགའ་བཀྲ་ཤིས།
      base_file: 9e9a.txt
      order: 7
    f808:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་པར་བཤད་པ་ཐུབ་བསྟན་གསལ་བའི་སྒྲོན་མེ་ཞེས་བྱ་བ་ལས་སྐབས་གཉིས་པའི་རྣམ་པར་བཤད་པ།
      author: དགེ་སློང་ཀུན་དགའ་བཀྲ་ཤིས།
      base_file: f808.txt
      order: 8
    b21a:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་པར་བཤད་པ་ཐུབ་བསྟན་གསལ་བའི་སྒྲོན་མེ་ལས་སྐབས་གསུམ་པའི་རྣམ་པར་བཤད་པ།
      author: དགེ་སློང་ཀུན་དགའ་བཀྲ་ཤིས།
      base_file: b21a.txt
      order: 9
    73b3:
      title: སྡོམ་གསུམ་རྣམ་བཤད་རྒྱུད་བཞི་མཛེས་རྒྱན།
      author: མང་ཐོས་སློབ་མ་རིན་སྡིང་པ་ནམ་མཁའ་རྒྱལ་མཚན།
      base_file: 73b3.txt
      order: 10
    88d3:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བ་ལས་གནས་གསུམ་གསལ་བྱེད།
      author: འབྲས་ཡུལ་ཀུན་དགའ་ཆོས་བཟང་།
      base_file: 88d3.txt
      order: 11
    ee82:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་སྤྱི་དོན་སྡོམ་གསུམ་གནད་ཀྱི་གསལ་བྱེད།
      author: འབྲས་ཡུལ་ཀུན་དགའ་ཆོས་བཟང་།
      base_file: ee82.txt
      order: 12
    08d3:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཊཱི་ཀ་བསྟན་པའི་སྒྲོན་མེ་ལས་སོ་ཐར་སྡོམ་པའི་རྣམ་བཤད།
      author: པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན་གྱི་སློབ་མ་དགེ་སློང་དོན་ཡོད་གྲུབ་པ།
      base_file: 08d3.txt
      order: 13
    c04b:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཊཱི་ཀ་བསྟན་པའི་སྒྲོན་མེ་ལས་བྱང་སེམས་སྡོམ་པའི་རྣམ་བཤད།
      author: པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན་གྱི་སློབ་མ་དགེ་སློང་དོན་ཡོད་གྲུབ་པ།
      base_file: c04b.txt
      order: 14
    6a5d:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཊཱི་ཀ་བསྟན་པའི་སྒྲོན་མེ་ལས་སྔགས་སྡོམ་གྱི་རྣམ་བཤད།
      author: པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན་གྱི་སློབ་མ་དགེ་སློང་དོན་ཡོད་གྲུབ་པ།
      base_file: 6a5d.txt
      order: 15
    9ecc:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་སྤྱི་དོན་ཀུན་གསལ་ནོར་བུའི་ཕྲེང་བ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མཁན་ཆེན་ངག་ཆོས།
      base_file: 9ecc.txt
      order: 16
    8dc8:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་ཁ་སྐོང་གཞི་ལམ་འབྲས་གསུམ་གསལ་བར་བྱེད་པའི་ལེགས་བཤད་འོད་ཀྱི་སྣང་བ།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: 8dc8.txt
      order: 17
    781e:
      title: སྡོམ་པ་གསུམ་ཁ་སྐོང་གི་རྣམ་བཤད་ལེགས་པར་བཤད་པ་ནོར་བུའི་ཕྲེང་བ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མང་ཐོས་ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
      base_file: 781e.txt
      order: 18
    d2ce:
      title: སྡོམ་པ་གསུམ་གྱི་བསྟན་བཅོས་ལ་དྲིས་ཤིང་རྩོད་པའི་ལན་སྡོམ་གསུམ་འཁྲུལ་སྤོང་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: d2ce.txt
      order: 19
    b435:
      title: སྡོམ་པ་གསུམ་གྱི་རབ་ཏུ་དབྱེ་བའི་རྣམ་བཤད་ལེགས་པར་བཤད་པ་ཟླ་འོད་ནོར་བུ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: མཁན་ཆེན་ངག་ཆོས།
      base_file: b435.txt
      order: 20
    6cd3:
      title: སྡོམ་པ་གསུམ་ཁ་སྐོང་གི་རྣམ་བཤད་ལེགས་པར་བཤད་པ་རྒྱན་གྱི་མེ་ཏོག་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: མཁན་ཆེན་ངག་ཆོས།
      base_file: 6cd3.txt
      order: 21
    0dca:
      title: སྡེ་དགེ་རྒྱལ་པོས་མཛད་པའི་གྲུབ་མཐའ་བཞི་དང་རྒྱུད་སྡེ་བཞི་ཡི་རྣམ་གཞག་བསྟན་པའི་སྙིང་པོ་སྡོམ་པ་གསུམ་གྱི་དོན་གཞི་ལམ་འབྲས་གསུམ་གྱི་གནད་བསྡུས་ཞར་བྱུང་བོད་ཀྱི་གྲུབ་མཐའི་ལོ་རྒྱུས་བཅས་ལྷན་ཅིག་ཏུ་བཀོད་པ་མདོ་སྔགས་ཆོས་ཚུལ་སྙིང་པོའི་གསལ་བྱེད་མ་རིག་མུན་པ་སེལ་བའི་དཔལ་ལྡན་འོད་ཟེར་བརྒྱ་པ་སྐལ་བཟང་བློ་ཡི་པད་ཚལ་བཞད་པ་དོན་གཉིས་ལྷུན་གྱིས་གྲུབ་པའི་ལམ་བཟང་ཞེས་བྱ་བ།
      author: སྡེ་དགེ་རྒྱལ་པོ།
      base_file: 0dca.txt
      order: 22
created_at: '2022-04-06T16:24:47.180674'
last_modified_at: '2022-04-06T16:24:47.180685'
